"""Reporting for the username feature — and what it refuses to report.

The trips drawer shipped measurable by nothing: trips were counted, drives were
counted, and the one feature with a stated purpose had no number attached to
it. These tests pin both halves of the fix.

**What is counted.** Claims and releases are recorded by the server, so they
cannot be blocked or forged; adoption is read from the `trips` table, so an ad
blocker cannot move it; and "came back" needs a real gap, or two legs of one
holiday planned in one sitting would read as retention.

**What is not.** No username reaches `app_events`, no username reaches the
console, and no endpoint here can be drilled into a list of people. That is the
same rule `events.normalize_path` enforces on `/u/<name>`, and it would be
pointless there if this module gave the names back on another screen.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timedelta

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.core.database import Base, get_db
from app.core.visitor import owner_hash
from app.main import app
from app.models import AppEvent, Profile, Trip, Vehicle
from app.services import profiles
from app.services.analytics import Filters
from app.services.usage import ALLOWED_EVENTS, usage_stats
from tests.test_api import BORN_SEED

SECRET = "3f2a1b4c-5d6e-4f70-8192-a3b4c5d6e7f8"
SECRET2 = "9e8d7c6b-5a49-4382-b716-0f1e2d3c4b5a"


@pytest_asyncio.fixture
async def db_session():
    engine = create_async_engine("sqlite+aiosqlite://")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    maker = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with maker() as session:
        session.add(Vehicle(**BORN_SEED))
        await session.commit()
        yield session
    await engine.dispose()


@pytest_asyncio.fixture
async def client(db_session):
    async def override_get_db():
        yield db_session

    app.dependency_overrides[get_db] = override_get_db
    async with AsyncClient(
        transport=ASGITransport(app=app), base_url="http://test"
    ) as c:
        yield c
    app.dependency_overrides.clear()


async def _vehicle_id(db: AsyncSession) -> uuid.UUID:
    return (await db.execute(select(Vehicle.id))).scalars().first()


async def _trip(db: AsyncSession, *, owner: str | None, days_ago: float = 0.0) -> Trip:
    """A trip row, written directly.

    Straight to the table rather than through `POST /api/trips`: what is under
    test is the counting, and a real plan would drag in a route, a charger set
    and a simulator run to produce the one column that matters here.
    """
    trip = Trip(
        vehicle_id=await _vehicle_id(db),
        owner_hash=owner,
        request={},
        result={},
        created_at=datetime.utcnow() - timedelta(days=days_ago),
    )
    db.add(trip)
    await db.commit()
    return trip


async def _event(db: AsyncSession, name: str, *, path: str | None = None) -> None:
    db.add(AppEvent(name=name, path=path, visitor=uuid.uuid4().hex[:32]))
    await db.commit()


class TestTheEventsAreServerSide:
    """A claim is a state change; only the server knows one happened."""

    @pytest.mark.asyncio
    @pytest.mark.parametrize("name", ["profile_claimed", "profile_released"])
    async def test_the_public_endpoint_refuses_them(self, client: AsyncClient, name):
        """Otherwise "names claimed" is a number anyone can type in — and it is
        cross-checked against the `profiles` table precisely so it cannot be."""
        res = await client.post("/api/events", json={"name": name, "path": "/"})
        assert res.status_code == 422

    @pytest.mark.asyncio
    async def test_the_drawer_event_is_accepted_from_a_browser(self, client: AsyncClient):
        """The drawer is a panel, not a route — no page view is generated by
        opening it, so this is the only evidence it was used."""
        res = await client.post("/api/events", json={"name": "trips_opened", "path": "/"})
        assert res.status_code == 204

    @pytest.mark.asyncio
    async def test_claiming_records_one_event_with_no_name_in_it(
        self, client: AsyncClient, db_session: AsyncSession
    ):
        res = await client.post(
            "/api/users", json={"username": "marc"}, headers={"X-Owner-Secret": SECRET}
        )
        assert res.status_code == 201

        rows = (
            await db_session.execute(
                select(AppEvent).where(AppEvent.name == "profile_claimed")
            )
        ).scalars().all()
        assert len(rows) == 1
        row = rows[0]
        # The whole point: a count, not a record of who.
        assert row.path is None
        assert row.client_id is None
        assert "marc" not in str(row.__dict__.values())

    @pytest.mark.asyncio
    async def test_an_idempotent_reclaim_is_not_a_second_claim(
        self, client: AsyncClient, db_session: AsyncSession
    ):
        """A retry over a flaky connection is not a second person picking a
        name, and counting it would push the claim count above the profiles
        table it is checked against."""
        headers = {"X-Owner-Secret": SECRET}
        assert (
            await client.post("/api/users", json={"username": "marc"}, headers=headers)
        ).status_code == 201
        assert (
            await client.post("/api/users", json={"username": "marc"}, headers=headers)
        ).status_code == 200

        n = len(
            (
                await db_session.execute(
                    select(AppEvent).where(AppEvent.name == "profile_claimed")
                )
            ).scalars().all()
        )
        assert n == 1

    @pytest.mark.asyncio
    async def test_releasing_leaves_the_only_trace_there_is(
        self, client: AsyncClient, db_session: AsyncSession
    ):
        """Releasing deletes the profile row and its `created_at` with it. If
        this event were missing, a name claimed and given back inside one window
        would be invisible in both directions."""
        headers = {"X-Owner-Secret": SECRET}
        await client.post("/api/users", json={"username": "marc"}, headers=headers)
        assert (await client.delete("/api/users/marc", headers=headers)).status_code == 204

        assert (await db_session.execute(select(Profile))).scalars().all() == []
        names = [
            r.name
            for r in (await db_session.execute(select(AppEvent))).scalars().all()
        ]
        assert names.count("profile_released") == 1

    @pytest.mark.asyncio
    async def test_a_failed_claim_counts_nothing(
        self, client: AsyncClient, db_session: AsyncSession
    ):
        res = await client.post(
            "/api/users", json={"username": "me"}, headers={"X-Owner-Secret": SECRET}
        )
        assert res.status_code == 422
        assert (await db_session.execute(select(AppEvent))).scalars().all() == []

    def test_every_name_is_in_the_allowlist(self):
        """`events.py` checks against this set, so a name recorded but not
        listed would be a row the read side never counts."""
        assert {
            profiles.CLAIMED_EVENT,
            profiles.RELEASED_EVENT,
            profiles.DRAWER_EVENT,
        } <= ALLOWED_EVENTS


class TestTheNumbers:
    @pytest.mark.asyncio
    async def test_adoption_is_measured_against_the_trips_table(
        self, db_session: AsyncSession
    ):
        """Not against `trip_planned` events: those can be blocked, and the
        share would then be a ratio of two differently-sampled populations."""
        db_session.add(Profile(username="marc", owner_hash=owner_hash(SECRET)))
        await db_session.commit()
        await _trip(db_session, owner=owner_hash(SECRET))
        await _trip(db_session, owner=owner_hash(SECRET))
        await _trip(db_session, owner=None)
        await _trip(db_session, owner=None)

        s = await profiles.name_stats(db_session, Filters.window(7))
        assert (s.trips, s.named_trips) == (4, 2)
        assert s.named_share == 0.5
        assert s.active == 1

    @pytest.mark.asyncio
    async def test_a_quiet_window_is_not_zero_percent(self, db_session: AsyncSession):
        """"0% of no trips" reads as a feature nobody wants; None renders as a
        dash, which is the truth."""
        s = await profiles.name_stats(db_session, Filters.window(7))
        assert s.named_share is None
        assert s.return_rate is None

    @pytest.mark.asyncio
    async def test_a_name_holding_nothing_is_dormant(self, db_session: AsyncSession):
        db_session.add(Profile(username="marc", owner_hash=owner_hash(SECRET)))
        db_session.add(Profile(username="ada", owner_hash=owner_hash(SECRET2)))
        await db_session.commit()
        await _trip(db_session, owner=owner_hash(SECRET))

        s = await profiles.name_stats(db_session, Filters.window(7))
        assert (s.live, s.with_trips, s.dormant) == (2, 1, 1)

    @pytest.mark.asyncio
    async def test_coming_back_needs_a_day_not_a_second_trip(
        self, db_session: AsyncSession
    ):
        """Two legs of one holiday planned in one sitting is one visit.
        Counting it would flatter every name into looking retained."""
        db_session.add(Profile(username="marc", owner_hash=owner_hash(SECRET)))
        db_session.add(Profile(username="ada", owner_hash=owner_hash(SECRET2)))
        await db_session.commit()

        # Same sitting.
        await _trip(db_session, owner=owner_hash(SECRET))
        await _trip(db_session, owner=owner_hash(SECRET))
        # Came back a fortnight later.
        await _trip(db_session, owner=owner_hash(SECRET2), days_ago=14)
        await _trip(db_session, owner=owner_hash(SECRET2))

        s = await profiles.name_stats(db_session, Filters.window(90))
        assert s.returning == 1
        assert s.with_trips == 2
        # Against names that HOLD trips, never against every name.
        assert s.return_rate == 0.5

    @pytest.mark.asyncio
    async def test_the_spread_buckets_by_trips_per_name(self, db_session: AsyncSession):
        db_session.add(Profile(username="marc", owner_hash=owner_hash(SECRET)))
        db_session.add(Profile(username="ada", owner_hash=owner_hash(SECRET2)))
        await db_session.commit()
        await _trip(db_session, owner=owner_hash(SECRET))
        for _ in range(4):
            await _trip(db_session, owner=owner_hash(SECRET2))

        s = await profiles.name_stats(db_session, Filters.window(7))
        got = {b.label: b.value for b in s.spread}
        assert got["1 trip"] == 1
        assert got["3-5 trips"] == 1
        assert sum(got.values()) == 2

    @pytest.mark.asyncio
    async def test_panel_opens_and_list_views_are_counted_apart(
        self, db_session: AsyncSession
    ):
        """One is intent (somebody went looking for a trip they planned), the
        other is a stranger reading a shared list. Summing them would answer
        neither question."""
        await _event(db_session, "trips_opened")
        await _event(db_session, "trips_opened")
        await _event(db_session, "page_view", path="/u/:username")
        await _event(db_session, "page_view", path="/")

        s = await profiles.name_stats(db_session, Filters.window(7))
        assert (s.drawer_opens, s.list_views) == (2, 1)

    @pytest.mark.asyncio
    async def test_lifetime_numbers_ignore_the_window(self, db_session: AsyncSession):
        """A name is not a windowed thing. Scoped to seven days, every one of
        these reads zero on a quiet week and looks like a dead feature."""
        db_session.add(Profile(username="marc", owner_hash=owner_hash(SECRET)))
        await db_session.commit()
        await _trip(db_session, owner=owner_hash(SECRET), days_ago=200)

        s = await profiles.name_stats(db_session, Filters.window(1))
        assert (s.live, s.with_trips) == (1, 1)
        # …while the window-scoped adoption numbers correctly see nothing.
        assert s.trips == 0


class TestNothingLeaksAName:
    @pytest.mark.asyncio
    async def test_the_wire_shape_carries_no_username(self, db_session: AsyncSession):
        """The console renders whatever this returns. A username in it would
        undo `events.normalize_path` collapsing `/u/<name>` two files over."""
        db_session.add(Profile(username="marc", owner_hash=owner_hash(SECRET)))
        await db_session.commit()
        await _trip(db_session, owner=owner_hash(SECRET))

        payload = profiles.as_dict(
            await profiles.name_stats(db_session, Filters.window(7))
        )
        blob = str(payload)
        assert "marc" not in blob
        assert owner_hash(SECRET) not in blob

    @pytest.mark.asyncio
    async def test_the_stats_endpoint_agrees_with_the_service(
        self, db_session: AsyncSession
    ):
        """One reader, so the terminal report and the console cannot disagree
        about what an "active name" is — the rule `services/corridors.py`
        already lives by."""
        db_session.add(Profile(username="marc", owner_hash=owner_hash(SECRET)))
        await db_session.commit()
        await _trip(db_session, owner=owner_hash(SECRET))
        await _trip(db_session, owner=None)

        direct = await profiles.name_stats(db_session, Filters.window(7))
        stats = await usage_stats(db_session, days=7)
        assert stats.names is not None
        assert stats.names.live == direct.live
        assert stats.names.named_trips == direct.named_trips
        assert stats.names.named_share == direct.named_share
        assert [(b.label, b.count) for b in stats.names.spread] == [
            (b.label, b.value) for b in direct.spread
        ]
