"""The persistent pseudonym: what it accepts, what it refuses, and what it means.

This is the one piece of the analytics design that deliberately reverses an
earlier decision — `visitor_hash` rotates nightly precisely so nobody can be
followed, and this follows them. What keeps that defensible is a short list of
properties, and each one has a test here:

* it is generated by the browser and never derived from the request, so
  clearing site data really does end it;
* anything not matching a v4 UUID exactly is discarded, because the header
  arrives on an unauthenticated public endpoint;
* what we store is a hash, so the value in the database is not the value in
  the browser;
* the daily pseudonym still counts people who send nothing, so opting out
  costs a retention number and not a headcount;
* only the person who PLANS a trip is recorded against it — never someone who
  opens a share link.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timedelta

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.core.database import Base, get_db
from app.core.visitor import client_hash, request_client_id
from app.main import app
from app.models import AppEvent, TripStat, Vehicle
from app.services.geo import RouteGeometry
from app.services.routing import RouteData
from app.services.simulator import ChargerNode
from app.services.usage import usage_stats
from tests.fixtures import nl_to_austria_route
from tests.test_api import BORN_SEED, plan_body, vehicle_id

CID = "3f2a1b4c-5d6e-4f70-8192-a3b4c5d6e7f8"
CID2 = "9e8d7c6b-5a49-4382-b716-0f1e2d3c4b5a"


def _request_with(header_value: str | None):
    """A bare Starlette request carrying (or not carrying) the header."""
    from starlette.requests import Request

    headers = []
    if header_value is not None:
        headers.append((b"x-client-id", header_value.encode()))
    return Request(
        {
            "type": "http",
            "method": "POST",
            "path": "/api/events",
            "headers": headers,
            "client": ("1.2.3.4", 1234),
        }
    )


class TestValidation:
    def test_a_v4_uuid_is_accepted(self):
        assert request_client_id(_request_with(CID)) == client_hash(CID)

    def test_case_is_normalised(self):
        """Some clients upper-case hex. The same browser must not become two
        people because of it."""
        assert request_client_id(_request_with(CID.upper())) == client_hash(CID)

    @pytest.mark.parametrize(
        "value",
        [
            None,
            "",
            "   ",
            "not-a-uuid",
            "3f2a1b4c5d6e4f708192a3b4c5d6e7f8",          # no dashes
            "3f2a1b4c-5d6e-1f70-8192-a3b4c5d6e7f8",      # v1, not v4
            "3f2a1b4c-5d6e-4f70-0192-a3b4c5d6e7f8",      # bad variant nibble
            "3f2a1b4c-5d6e-4f70-8192-a3b4c5d6e7f8x",     # trailing junk
            "'; DROP TABLE app_events; --",
            "x" * 5000,
        ],
    )
    def test_anything_else_is_discarded(self, value):
        """The header is hostile input on a public endpoint. A caller must not
        be able to write a string of their choosing into the database."""
        assert request_client_id(_request_with(value)) is None

    def test_the_stored_value_is_not_the_browsers_value(self):
        """If an id ever leaks into a URL or a screenshot, it must not be
        usable to go looking for that person's rows."""
        assert client_hash(CID) != CID
        assert CID not in client_hash(CID)
        assert len(client_hash(CID)) == 32

    def test_it_does_not_rotate(self):
        """The opposite of `visitor_hash`, on purpose — this is the whole
        feature. If it ever starts rotating, retention silently reads zero."""
        assert client_hash(CID) == client_hash(CID)

    def test_different_browsers_differ(self):
        assert client_hash(CID) != client_hash(CID2)


# ---------------------------------------------------------------------------
# Through the API
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def db_session():
    engine = create_async_engine("sqlite+aiosqlite://")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    maker = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with maker() as session:
        session.add(Vehicle(**BORN_SEED))
        await session.commit()
        yield session
    await engine.dispose()


@pytest_asyncio.fixture
async def client(db_session, monkeypatch):
    async def override_get_db():
        yield db_session

    app.dependency_overrides[get_db] = override_get_db
    segments, charger_nodes = nl_to_austria_route()
    route = RouteData(
        geometry=RouteGeometry([(52.09, 5.12), (47.26, 11.39)]),
        segments=segments,
        total_dist_m=sum(s.dist_m for s in segments),
        total_dur_s=sum(s.dist_m for s in segments) / 30.0,
    )

    async def fake_get_route(db, o_lat, o_lon, d_lat, d_lon):
        return route

    async def fake_chargers(db, r) -> list[ChargerNode]:
        return charger_nodes

    monkeypatch.setattr("app.api.trips.routing.get_route", fake_get_route)
    monkeypatch.setattr("app.api.trips.chargers_svc.chargers_for_route", fake_chargers)

    async with AsyncClient(
        transport=ASGITransport(app=app), base_url="http://test"
    ) as c:
        yield c
    app.dependency_overrides.clear()


class TestEvents:
    async def test_the_id_is_recorded_when_sent(self, client, db_session):
        resp = await client.post(
            "/api/events",
            json={"name": "page_view", "path": "/"},
            headers={"X-Client-Id": CID},
        )
        assert resp.status_code == 204
        row = (await db_session.execute(select(AppEvent))).scalars().one()
        assert row.client_id == client_hash(CID)

    async def test_without_the_header_the_visit_is_still_counted(
        self, client, db_session
    ):
        """Opting out costs a retention number, not a headcount — which is why
        the daily `visitor` pseudonym was kept rather than replaced."""
        resp = await client.post("/api/events", json={"name": "page_view", "path": "/"})
        assert resp.status_code == 204
        row = (await db_session.execute(select(AppEvent))).scalars().one()
        assert row.client_id is None
        assert len(row.visitor) == 32  # still counted today

    async def test_a_junk_header_does_not_reject_the_event(self, client, db_session):
        """Discarding the id must not discard the count with it."""
        resp = await client.post(
            "/api/events",
            json={"name": "page_view", "path": "/"},
            headers={"X-Client-Id": "haha"},
        )
        assert resp.status_code == 204
        row = (await db_session.execute(select(AppEvent))).scalars().one()
        assert row.client_id is None


class TestTripStats:
    async def test_planning_records_the_planner(self, client, db_session):
        resp = await client.post(
            "/api/trips",
            json=plan_body(await vehicle_id(client)),
            headers={"X-Client-Id": CID},
        )
        assert resp.status_code == 200, resp.text
        stat = (await db_session.execute(select(TripStat))).scalar_one()
        assert stat.client_id == client_hash(CID)

    async def test_the_id_never_reaches_the_trip_itself(self, client, db_session):
        """It must land on the coarsened row and nowhere else. `Trip.request`
        holds exact coordinates; a pseudonym in there is the one join this
        whole design exists to prevent."""
        from app.models import Trip

        resp = await client.post(
            "/api/trips",
            json=plan_body(await vehicle_id(client)),
            headers={"X-Client-Id": CID},
        )
        trip = await db_session.get(Trip, uuid.UUID(resp.json()["id"]))
        blob = f"{trip.request}{trip.result}"
        assert CID not in blob
        assert client_hash(CID) not in blob

    async def test_reading_a_shared_trip_records_nobody(self, client, db_session):
        """Opening a link someone forwarded you is not using the app. If this
        ever fails, the share token has become a record of who was sent it."""
        vid = await vehicle_id(client)
        tid = (
            await client.post(
                "/api/trips", json=plan_body(vid), headers={"X-Client-Id": CID}
            )
        ).json()["id"]

        before = (
            await db_session.execute(select(func.count()).select_from(AppEvent))
        ).scalar_one()
        resp = await client.get(f"/api/trips/{tid}", headers={"X-Client-Id": CID2})
        assert resp.status_code == 200
        after = (
            await db_session.execute(select(func.count()).select_from(AppEvent))
        ).scalar_one()
        assert after == before, "reading a trip wrote a row about the reader"

        # And the viewer is nowhere on the trip's own stat row.
        stat = (await db_session.execute(select(TripStat))).scalar_one()
        assert stat.client_id == client_hash(CID)

    async def test_deleting_a_trip_takes_the_planner_id_with_it(
        self, client, db_session
    ):
        vid = await vehicle_id(client)
        tid = (
            await client.post(
                "/api/trips", json=plan_body(vid), headers={"X-Client-Id": CID}
            )
        ).json()["id"]
        assert (await client.delete(f"/api/trips/{tid}")).status_code == 204
        assert (
            await db_session.execute(select(func.count()).select_from(TripStat))
        ).scalar_one() == 0


class TestRetentionNumbers:
    async def _visit(self, client, cid: str):
        await client.post(
            "/api/events",
            json={"name": "page_view", "path": "/"},
            headers={"X-Client-Id": cid},
        )

    async def test_a_first_visit_is_not_a_return(self, client, db_session):
        await self._visit(client, CID)
        stats = await usage_stats(db_session, days=7)
        assert stats.identified_visitors == 1
        assert stats.returning_visitors == 0

    async def test_two_visits_inside_the_window_are_still_one_visit(
        self, client, db_session
    ):
        """Reading two pages after landing from a link is not retention, and
        counting it as such would flatter every launch spike."""
        await self._visit(client, CID)
        await self._visit(client, CID)
        stats = await usage_stats(db_session, days=7)
        assert stats.identified_visitors == 1
        assert stats.returning_visitors == 0

    async def test_coming_back_after_the_window_counts(self, client, db_session):
        await self._visit(client, CID)
        old = (await db_session.execute(select(AppEvent))).scalars().one()
        old.at = datetime.utcnow() - timedelta(days=30)
        await db_session.commit()

        await self._visit(client, CID)      # returned today
        await self._visit(client, CID2)     # brand new
        stats = await usage_stats(db_session, days=7)
        assert stats.identified_visitors == 2
        assert stats.returning_visitors == 1

    async def test_visitors_without_an_id_are_outside_the_denominator(
        self, client, db_session
    ):
        """Someone on Global Privacy Control counts toward `visitors` and not
        toward retention — so the ratio stays honest rather than being diluted
        by people who could never have been recognised."""
        await self._visit(client, CID)
        await client.post("/api/events", json={"name": "page_view", "path": "/"})
        stats = await usage_stats(db_session, days=7)
        assert stats.identified_visitors == 1
        assert stats.visitors == 1  # one IP/UA pair in this test client


class TestIdRetention:
    async def test_old_planner_ids_are_cleared_but_the_corridor_is_kept(
        self, client, db_session
    ):
        """15 months, not 90 days — a holiday app's cycle is annual. The row
        survives so the corridor history does; only the person expires."""
        import scripts.purge_old_trip_stat_ids as mod
        from scripts.purge_old_trip_stat_ids import RETENTION_DAYS, purge

        await client.post(
            "/api/trips",
            json=plan_body(await vehicle_id(client)),
            headers={"X-Client-Id": CID},
        )
        stat = (await db_session.execute(select(TripStat))).scalar_one()
        stat.created_at = datetime.utcnow() - timedelta(days=RETENTION_DAYS + 10)
        await db_session.commit()

        class _Maker:
            def __call__(self):
                return self

            async def __aenter__(self):
                return db_session

            async def __aexit__(self, *a):
                return False

        original = mod.AsyncSessionLocal
        mod.AsyncSessionLocal = _Maker()
        try:
            assert await purge(days=RETENTION_DAYS, apply=False) == 1
            await db_session.refresh(stat)
            assert stat.client_id is not None, "dry run changed something"

            assert await purge(days=RETENTION_DAYS, apply=True) == 1
            await db_session.refresh(stat)
            assert stat.client_id is None
            # The corridor itself is history worth keeping.
            assert stat.origin_gh and stat.distance_km > 0
        finally:
            mod.AsyncSessionLocal = original

    def test_the_window_can_see_a_full_year(self):
        """Under ~13 months this cannot answer "did last August come back this
        August", which is the only retention question this app really has."""
        from scripts.purge_old_trip_stat_ids import RETENTION_DAYS

        assert RETENTION_DAYS >= 395
