"""add the persistent client_id to app_events and trip_stats

Revision ID: 0007_client_id
Revises: 0006_trip_stats
Create Date: 2026-08-10 00:00:00.000000

Nullable on both tables, with no backfill and no default — there is nothing to
backfill from. The pseudonym is generated by the browser, so every row written
before this deploy has no answer, and inventing one would make retention look
like it started earlier than it did.

`app_events.client_id` gets no index: every query there is already bounded by
the `(at, name)` range scan, and retention joins two grouped subqueries rather
than looking a single pseudonym up. `trip_stats.client_id` does get one — it is
the join column for "how many trips does one person plan", and that table has
one row per trip rather than one per page view.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from app.core.migration_utils import has_column, has_table

revision = "0007_client_id"
down_revision = "0006_trip_stats"
branch_labels = None
depends_on = None


def upgrade() -> None:
    if has_table("app_events") and not has_column("app_events", "client_id"):
        op.add_column(
            "app_events", sa.Column("client_id", sa.String(length=32), nullable=True)
        )
    if has_table("trip_stats") and not has_column("trip_stats", "client_id"):
        op.add_column(
            "trip_stats", sa.Column("client_id", sa.String(length=32), nullable=True)
        )
        op.create_index("ix_trip_stats_client_id", "trip_stats", ["client_id"])


def downgrade() -> None:
    if has_table("trip_stats") and has_column("trip_stats", "client_id"):
        op.drop_index("ix_trip_stats_client_id", table_name="trip_stats")
        op.drop_column("trip_stats", "client_id")
    if has_table("app_events") and has_column("app_events", "client_id"):
        op.drop_column("app_events", "client_id")
